### ISSUE TITLE
Fix indices in Get.Configuration.Matrix.p1.FW

### ISSUE THREAD

**Issue by lizgross** [csprock/DMBHGraphs#13] opened 2019-11-27 01:37 UTC
Change lines 50-59 from

x[i,j,2,1]=1
x[j,i,1,2]=1

to

x[i,j,1,2]=1
x[j,i,2,1]=1

**Comment by csprock** [comment] 2019-11-27 01:39
duplicate of issue #5

**Closed by csprock** 2019-11-27 01:39 UTC
